// <auto-generated />
using System;
using LinhaDireta.Dados.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinhaDireta.Dados.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241104130817_AddLinhaDiretaHistorico")]
    partial class AddLinhaDiretaHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinhaDireta.Dominio.Entities.LinhaDiretaHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("LinhaDiretaMessageId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsavelAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StatusAtual")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TempoNoStatus")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("LinhaDiretaMessageId");

                    b.ToTable("LinhaDiretaHistorico");
                });

            modelBuilder.Entity("LinhaDireta.Dominio.Entities.LinhaDiretaMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsavelUltimaAtualizacaoId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("LinhaDiretaMessages");
                });

            modelBuilder.Entity("LinhaDireta.Dominio.Entities.StatusLinhaDireta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusLinhaDireta");
                });

            modelBuilder.Entity("LinhaDireta.Dominio.Entities.LinhaDiretaHistorico", b =>
                {
                    b.HasOne("LinhaDireta.Dominio.Entities.LinhaDiretaMessage", "LinhaDiretaMessage")
                        .WithMany("Historico")
                        .HasForeignKey("LinhaDiretaMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhaDiretaMessage");
                });

            modelBuilder.Entity("LinhaDireta.Dominio.Entities.LinhaDiretaMessage", b =>
                {
                    b.HasOne("LinhaDireta.Dominio.Entities.StatusLinhaDireta", "StatusLinhaDireta")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusLinhaDireta");
                });

            modelBuilder.Entity("LinhaDireta.Dominio.Entities.LinhaDiretaMessage", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
